apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpRENDQW5DZ0F3SUJBZ0lRVDN6eXNvbTJhejZEZ1RwYWY1QVBVekFOQmdrcWhraUc5dzBCQVFzRkFEQmUKTVE4d0RRWURWUVFEREFaTE9ITWdRMEV4Q3pBSkJnTlZCQVlUQWxWVE1ROHdEUVlEVlFRSERBWkJkWE4wYVc0eApEekFOQmdOVkJBb01Cazl5WVdOc1pURU1NQW9HQTFVRUN3d0RUMk5wTVE0d0RBWURWUVFJREFWVVpYaGhjekFlCkZ3MHlOVEV4TURVeE16TTRNakphRncwek1ERXhNRFV4TXpNNE1qSmFNRjR4RHpBTkJnTlZCQU1NQmtzNGN5QkQKUVRFTE1Ba0dBMVVFQmhNQ1ZWTXhEekFOQmdOVkJBY01Ca0YxYzNScGJqRVBNQTBHQTFVRUNnd0dUM0poWTJ4bApNUXd3Q2dZRFZRUUxEQU5QWTJreERqQU1CZ05WQkFnTUJWUmxlR0Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBejlyWWJSK3Y0VHo2R1p2akN1YkVSKzJlSVhXOFY4cmUrVFo4cyticktMaHUKR25yaFlIWVZNanZMTmxac2JDTkk0cnU5bFptdndCUEwyaEtoRE12Tm5BWWVkQU4zbEY3ODd1NVR4TjBsVldpRgphQnh3eWMvNTVCeVQyUlBzOUEwZjRzUm16SGxGcHhVUFpYZ01KNUp6bmdET096TVVUYmV0ZmlEc1NEMnRzSWZhCmQ2SDc3MzR5QXd6cFE5aG9WZGxHdDVMK1I0MEZrZ2E4emozd1F3Sy9wVW45TkpyY3U4YUdFUGg4U1ZMOGIwcjcKZlBNS3dSZFNuNTNmdDRack1yeWNFdnNWNjVjV3pvUDRXTVk2Nmp2MnJGSjRQWHJtVVVhSWhIQVNEMllBMmJBaQpVRmkyUk9PeHNzQ3NjaDNldEhzTXR3ODEvSXhvWk9WWVYvdGo3ekIxa1FJREFRQUJvMEl3UURBUEJnTlZIUk1CCkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQi93UUVBd0lCQmpBZEJnTlZIUTRFRmdRVXhadGVsQUdIcithK3lKaU4KR0NWKzVDUEdvM2t3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUJWeUY0YmZlL2JYTUtGYkMxQjVWVUkxamdDWgp4RTRZVmhWTnM0SEhyTjFUTzAxeEw0TWVrT2F5M1AyTmwrdURBRGRSVEQwMGM1akg1dlpXZFhBYlFCcGJCVXl3Cm91and1Mmc1emJ4N2NBbk90Mng2cHlrVFVUZ2xFUEtCM2JRY0Zodi9IaVM5Tk9OZCtvcUhQVTVSSFBYY3NZdm0KYWZzZmliZlNHOVBKMTlEUjZKQ0JsaTdLaWJyT0FXZitQOHNIdCtmQjhYZTRibDhIVGZRWmdKd1AzSFBlQlhONwpTQmpZRmdNTC9zdVp5VWYyNDdpdDJEYk1aWWIyc0NFNEZUR3VyYlhiRU9DTlFCQlozcVFkK3RsL21NUVNsS2tvCmRBclpiaFNIT0cvL3UvUzk5ckJBWFdoVkdyN0JSdEZLbjNvcUd5c2lrVUdsMWxSMmI0ODJPcDNyMDUwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://84.8.116.191:6443
  name: cluster-ctlh5pbdmka
contexts:
- context:
    cluster: cluster-ctlh5pbdmka
    user: gitlab-deployer
  name: gitlab-context
current-context: gitlab-context
users:
- name: gitlab-deployer
  user:
    token: 
