apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel-prod-ahm
type: Opaque
stringData:
  APP_KEY: base64:GpabfPfGyZhhWQrqcuG8PmrFyf1X65G6yx3Tp0hhFCE=

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laravel-prod-ahm
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "YourSecureRootPassword123!"
  MYSQL_DATABASE: "guapa_db"
  MYSQL_USER: "Admin"
  MYSQL_PASSWORD: "Sw&d2S2,yG4Z"

---
apiVersion: v1
kind: Secret
metadata:
  name: ocirsecret
  namespace: laravel-prod-ahm
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJsaW9uYXpjb3JwbGFuZGluZ3ByZGV1czJhY3IuYXp1cmVjci5pbyI6IHt9LAoJCSJtZS1yaXlhZGgtMS5vY2lyLmlvIjoge30KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSJkZWJ1ZyI6IHsKCQkJImhvb2tzIjogImV4ZWMiCgkJfSwKCQkic2NvdXQiOiB7CgkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9